<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PresentacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $presentaciones = [
            [
                'Nom_Presentacion' => 'Tableta',
                'Siglas' => 'TAB',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Cápsula',
                'Siglas' => 'CAP',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Jarabe',
                'Siglas' => 'JAR',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Inyección',
                'Siglas' => 'INY',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Crema',
                'Siglas' => 'CRE',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Ungüento',
                'Siglas' => 'UNG',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Suspensión',
                'Siglas' => 'SUS',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Polvo',
                'Siglas' => 'POL',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Gotas',
                'Siglas' => 'GOT',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Parche',
                'Siglas' => 'PAR',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Supositorio',
                'Siglas' => 'SUP',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Aerosol',
                'Siglas' => 'AER',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Líquido',
                'Siglas' => 'LIQ',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Gel',
                'Siglas' => 'GEL',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'Nom_Presentacion' => 'Pomada',
                'Siglas' => 'POM',
                'Estado' => 'Vigente',
                'Cod_Estado' => 'V',
                'Agregado_Por' => 'Sistema',
                'Agregadoel' => Carbon::now(),
                'Sistema' => 'POS',
                'ID_H_O_D' => 'Saluda',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($presentaciones as $presentacion) {
            DB::table('presentaciones')->insert($presentacion);
        }
    }
} 