<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Insertar datos de ejemplo en sucursales
        $sucursales = [
            [
                'nombre' => 'Clínica Central',
                'codigo' => 'CC001',
                'direccion' => 'Av. Principal 123, Centro',
                'telefono' => '02-123-4567',
                'email' => 'central@clinica.com',
                'responsable' => 'Dr. Juan Pérez',
                'telefono_responsable' => '099-123-4567',
                'descripcion' => 'Sucursal principal de la clínica',
                'estado' => 'activo',
                'zona' => 'Centro',
                'ciudad' => 'Guayaquil',
                'provincia' => 'Guayas',
                'codigo_postal' => '090101',
                'hora_apertura' => '08:00:00',
                'hora_cierre' => '18:00:00',
                'activa_ventas' => true,
                'activa_compras' => true,
                'activa_inventario' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Clínica Norte',
                'codigo' => 'CN001',
                'direccion' => 'Av. Norte 456, La Florida',
                'telefono' => '02-234-5678',
                'email' => 'norte@clinica.com',
                'responsable' => 'Dra. María González',
                'telefono_responsable' => '099-234-5678',
                'descripcion' => 'Sucursal norte de la clínica',
                'estado' => 'activo',
                'zona' => 'Norte',
                'ciudad' => 'Guayaquil',
                'provincia' => 'Guayas',
                'codigo_postal' => '090201',
                'hora_apertura' => '07:00:00',
                'hora_cierre' => '19:00:00',
                'activa_ventas' => true,
                'activa_compras' => true,
                'activa_inventario' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Clínica Sur',
                'codigo' => 'CS001',
                'direccion' => 'Av. Sur 789, Urdesa',
                'telefono' => '02-345-6789',
                'email' => 'sur@clinica.com',
                'responsable' => 'Dr. Carlos Rodríguez',
                'telefono_responsable' => '099-345-6789',
                'descripcion' => 'Sucursal sur de la clínica',
                'estado' => 'activo',
                'zona' => 'Sur',
                'ciudad' => 'Guayaquil',
                'provincia' => 'Guayas',
                'codigo_postal' => '090301',
                'hora_apertura' => '08:30:00',
                'hora_cierre' => '17:30:00',
                'activa_ventas' => true,
                'activa_compras' => true,
                'activa_inventario' => true,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        foreach ($sucursales as $sucursal) {
            DB::table('sucursales')->insert($sucursal);
        }

        // Insertar datos de ejemplo en consultorios
        $consultorios = [
            [
                'nombre' => 'Consultorio 1',
                'codigo' => 'C001',
                'descripcion' => 'Consultorio general con equipamiento básico',
                'sucursal_id' => 1,
                'piso' => '1',
                'numero_sala' => '101',
                'ubicacion_detallada' => 'Primer piso, al lado de recepción',
                'equipamiento' => 'Estetoscopio, tensiómetro, otoscopio',
                'caracteristicas_especiales' => 'Ventilación natural, buena iluminación',
                'accesible_discapacitados' => true,
                'aire_acondicionado' => true,
                'ventilacion_natural' => true,
                'hora_apertura' => '08:00:00',
                'hora_cierre' => '18:00:00',
                'estado' => 'activo',
                'disponible' => true,
                'creado_por' => 'Sistema',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Consultorio 2',
                'codigo' => 'C002',
                'descripcion' => 'Consultorio especializado en cardiología',
                'sucursal_id' => 1,
                'piso' => '1',
                'numero_sala' => '102',
                'ubicacion_detallada' => 'Primer piso, al lado del consultorio 1',
                'equipamiento' => 'Electrocardiógrafo, monitor cardíaco, desfibrilador',
                'caracteristicas_especiales' => 'Equipamiento cardiológico completo',
                'accesible_discapacitados' => true,
                'aire_acondicionado' => true,
                'ventilacion_natural' => false,
                'hora_apertura' => '08:00:00',
                'hora_cierre' => '18:00:00',
                'estado' => 'activo',
                'disponible' => true,
                'creado_por' => 'Sistema',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Consultorio 3',
                'codigo' => 'C003',
                'descripcion' => 'Consultorio de pediatría',
                'sucursal_id' => 1,
                'piso' => '2',
                'numero_sala' => '201',
                'ubicacion_detallada' => 'Segundo piso, área pediátrica',
                'equipamiento' => 'Estetoscopio pediátrico, balanza, tallímetro',
                'caracteristicas_especiales' => 'Decoración infantil, juguetes',
                'accesible_discapacitados' => true,
                'aire_acondicionado' => true,
                'ventilacion_natural' => true,
                'hora_apertura' => '08:00:00',
                'hora_cierre' => '17:00:00',
                'estado' => 'activo',
                'disponible' => true,
                'creado_por' => 'Sistema',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Consultorio Norte 1',
                'codigo' => 'CN001',
                'descripcion' => 'Consultorio general sucursal norte',
                'sucursal_id' => 2,
                'piso' => '1',
                'numero_sala' => 'N101',
                'ubicacion_detallada' => 'Primer piso, entrada principal',
                'equipamiento' => 'Estetoscopio, tensiómetro, otoscopio',
                'caracteristicas_especiales' => 'Ventilación natural, amplio',
                'accesible_discapacitados' => true,
                'aire_acondicionado' => false,
                'ventilacion_natural' => true,
                'hora_apertura' => '07:00:00',
                'hora_cierre' => '19:00:00',
                'estado' => 'activo',
                'disponible' => true,
                'creado_por' => 'Sistema',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'nombre' => 'Consultorio Sur 1',
                'codigo' => 'CS001',
                'descripcion' => 'Consultorio general sucursal sur',
                'sucursal_id' => 3,
                'piso' => '1',
                'numero_sala' => 'S101',
                'ubicacion_detallada' => 'Primer piso, área de consultas',
                'equipamiento' => 'Estetoscopio, tensiómetro, otoscopio',
                'caracteristicas_especiales' => 'Vista al jardín, tranquilo',
                'accesible_discapacitados' => true,
                'aire_acondicionado' => true,
                'ventilacion_natural' => true,
                'hora_apertura' => '08:30:00',
                'hora_cierre' => '17:30:00',
                'estado' => 'activo',
                'disponible' => true,
                'creado_por' => 'Sistema',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        foreach ($consultorios as $consultorio) {
            DB::table('consultorios')->insert($consultorio);
        }

        // Insertar datos de ejemplo en doctores
        $doctores = [
            [
                'Cedula_Profesional' => 'MD001',
                'Nombre_Completo' => 'Dr. Juan Carlos Pérez González',
                'Especialidad' => 'Medicina General',
                'Subespecialidad' => 'Medicina Familiar',
                'Telefono' => '099-111-1111',
                'Correo_Electronico' => 'juan.perez@clinica.com',
                'Direccion' => 'Av. Principal 123, Centro, Guayaquil',
                'Hora_Inicio_Laboral' => '08:00:00',
                'Hora_Fin_Laboral' => '17:00:00',
                'Duracion_Cita' => 30,
                'Costo_Consulta' => 45.00,
                'Consultorio_Asignado' => 'C001',
                'Estado' => 'Activo',
                'Notas' => 'Médico general con 15 años de experiencia',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Cedula_Profesional' => 'MD002',
                'Nombre_Completo' => 'Dra. María Elena González Rodríguez',
                'Especialidad' => 'Cardiología',
                'Subespecialidad' => 'Cardiología Intervencionista',
                'Telefono' => '099-222-2222',
                'Correo_Electronico' => 'maria.gonzalez@clinica.com',
                'Direccion' => 'Av. Norte 456, La Florida, Guayaquil',
                'Hora_Inicio_Laboral' => '08:00:00',
                'Hora_Fin_Laboral' => '18:00:00',
                'Duracion_Cita' => 45,
                'Costo_Consulta' => 80.00,
                'Consultorio_Asignado' => 'C002',
                'Estado' => 'Activo',
                'Notas' => 'Cardióloga especializada en procedimientos intervencionistas',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Cedula_Profesional' => 'MD003',
                'Nombre_Completo' => 'Dr. Carlos Alberto Rodríguez López',
                'Especialidad' => 'Pediatría',
                'Subespecialidad' => 'Neonatología',
                'Telefono' => '099-333-3333',
                'Correo_Electronico' => 'carlos.rodriguez@clinica.com',
                'Direccion' => 'Av. Sur 789, Urdesa, Guayaquil',
                'Hora_Inicio_Laboral' => '08:00:00',
                'Hora_Fin_Laboral' => '17:00:00',
                'Duracion_Cita' => 30,
                'Costo_Consulta' => 55.00,
                'Consultorio_Asignado' => 'C003',
                'Estado' => 'Activo',
                'Notas' => 'Pediatra con especialización en neonatología',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Cedula_Profesional' => 'MD004',
                'Nombre_Completo' => 'Dra. Ana Patricia López Martínez',
                'Especialidad' => 'Ginecología',
                'Subespecialidad' => 'Ginecología Oncológica',
                'Telefono' => '099-444-4444',
                'Correo_Electronico' => 'ana.lopez@clinica.com',
                'Direccion' => 'Av. Norte 456, La Florida, Guayaquil',
                'Hora_Inicio_Laboral' => '07:00:00',
                'Hora_Fin_Laboral' => '19:00:00',
                'Duracion_Cita' => 40,
                'Costo_Consulta' => 70.00,
                'Consultorio_Asignado' => 'CN001',
                'Estado' => 'Activo',
                'Notas' => 'Ginecóloga especializada en oncología',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Cedula_Profesional' => 'MD005',
                'Nombre_Completo' => 'Dr. Roberto Fernando Martínez Silva',
                'Especialidad' => 'Ortopedia',
                'Subespecialidad' => 'Traumatología Deportiva',
                'Telefono' => '099-555-5555',
                'Correo_Electronico' => 'roberto.martinez@clinica.com',
                'Direccion' => 'Av. Sur 789, Urdesa, Guayaquil',
                'Hora_Inicio_Laboral' => '08:30:00',
                'Hora_Fin_Laboral' => '17:30:00',
                'Duracion_Cita' => 45,
                'Costo_Consulta' => 75.00,
                'Consultorio_Asignado' => 'CS001',
                'Estado' => 'Activo',
                'Notas' => 'Ortopedista especializado en traumatología deportiva',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        foreach ($doctores as $doctor) {
            DB::table('doctores')->insert($doctor);
        }

        // Insertar datos de ejemplo en pacientes
        $pacientes = [
            [
                'Cedula' => '0901234567',
                'Nombre_Completo' => 'María Fernanda González López',
                'Fecha_Nacimiento' => '1985-03-15',
                'Sexo' => 'Femenino',
                'Telefono' => '099-666-6666',
                'Correo_Electronico' => 'maria.gonzalez@email.com',
                'Direccion' => 'Av. Principal 456, Centro, Guayaquil',
                'Grupo_Sanguineo' => 'O+',
                'Alergias' => 'Penicilina, polen',
                'Antecedentes_Medicos' => 'Hipertensión arterial, diabetes tipo 2',
                'Estado_Civil' => 'Casada',
                'Ocupacion' => 'Contadora',
                'Emergencia_Contacto' => 'Carlos González (Esposo)',
                'Emergencia_Telefono' => '099-777-7777',
                'Estado' => 'Activo',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Cedula' => '0902345678',
                'Nombre_Completo' => 'Luis Alberto Rodríguez Pérez',
                'Fecha_Nacimiento' => '1978-07-22',
                'Sexo' => 'Masculino',
                'Telefono' => '099-888-8888',
                'Correo_Electronico' => 'luis.rodriguez@email.com',
                'Direccion' => 'Av. Norte 789, La Florida, Guayaquil',
                'Grupo_Sanguineo' => 'A+',
                'Alergias' => 'Ninguna conocida',
                'Antecedentes_Medicos' => 'Hipercolesterolemia',
                'Estado_Civil' => 'Soltero',
                'Ocupacion' => 'Ingeniero',
                'Emergencia_Contacto' => 'Ana Rodríguez (Hermana)',
                'Emergencia_Telefono' => '099-999-9999',
                'Estado' => 'Activo',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Cedula' => '0903456789',
                'Nombre_Completo' => 'Carmen Elena Silva Martínez',
                'Fecha_Nacimiento' => '1992-11-08',
                'Sexo' => 'Femenino',
                'Telefono' => '099-000-0000',
                'Correo_Electronico' => 'carmen.silva@email.com',
                'Direccion' => 'Av. Sur 123, Urdesa, Guayaquil',
                'Grupo_Sanguineo' => 'B+',
                'Alergias' => 'Látex, mariscos',
                'Antecedentes_Medicos' => 'Asma bronquial',
                'Estado_Civil' => 'Divorciada',
                'Ocupacion' => 'Enfermera',
                'Emergencia_Contacto' => 'Pedro Silva (Padre)',
                'Emergencia_Telefono' => '099-111-0000',
                'Estado' => 'Activo',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Cedula' => '0904567890',
                'Nombre_Completo' => 'Roberto Carlos Pérez Silva',
                'Fecha_Nacimiento' => '1965-05-12',
                'Sexo' => 'Masculino',
                'Telefono' => '099-222-1111',
                'Correo_Electronico' => 'roberto.perez@email.com',
                'Direccion' => 'Av. Principal 789, Centro, Guayaquil',
                'Grupo_Sanguineo' => 'AB+',
                'Alergias' => 'Sulfamidas',
                'Antecedentes_Medicos' => 'Hipertensión arterial, enfermedad coronaria',
                'Estado_Civil' => 'Casado',
                'Ocupacion' => 'Abogado',
                'Emergencia_Contacto' => 'Lucía Pérez (Esposa)',
                'Emergencia_Telefono' => '099-333-2222',
                'Estado' => 'Activo',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Cedula' => '0905678901',
                'Nombre_Completo' => 'Ana Patricia López González',
                'Fecha_Nacimiento' => '1988-09-30',
                'Sexo' => 'Femenino',
                'Telefono' => '099-444-3333',
                'Correo_Electronico' => 'ana.lopez@email.com',
                'Direccion' => 'Av. Norte 321, La Florida, Guayaquil',
                'Grupo_Sanguineo' => 'O-',
                'Alergias' => 'Polvo, ácaros',
                'Antecedentes_Medicos' => 'Rinitis alérgica',
                'Estado_Civil' => 'Soltera',
                'Ocupacion' => 'Diseñadora',
                'Emergencia_Contacto' => 'María López (Madre)',
                'Emergencia_Telefono' => '099-555-4444',
                'Estado' => 'Activo',
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        foreach ($pacientes as $paciente) {
            DB::table('pacientes')->insert($paciente);
        }

        // Insertar datos de ejemplo en agendas
        $agendas = [
            [
                'Titulo_Cita' => 'Consulta General - Control Rutinario',
                'Descripcion' => 'Control rutinario de salud general',
                'Fecha_Cita' => now()->addDays(1)->format('Y-m-d'),
                'Hora_Inicio' => '09:00:00',
                'Hora_Fin' => '09:30:00',
                'Estado_Cita' => 'Confirmada',
                'Tipo_Cita' => 'Control',
                'Consultorio' => 'C001',
                'Costo' => 45.00,
                'Notas_Adicionales' => 'Paciente solicita control de presión arterial',
                'Fk_Paciente' => 1,
                'Fk_Doctor' => 1,
                'Fk_Sucursal' => 1,
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Titulo_Cita' => 'Consulta Cardiológica - Evaluación',
                'Descripcion' => 'Evaluación cardiológica completa',
                'Fecha_Cita' => now()->addDays(2)->format('Y-m-d'),
                'Hora_Inicio' => '10:00:00',
                'Hora_Fin' => '10:45:00',
                'Estado_Cita' => 'Pendiente',
                'Tipo_Cita' => 'Consulta',
                'Consultorio' => 'C002',
                'Costo' => 80.00,
                'Notas_Adicionales' => 'Traer resultados de análisis previos',
                'Fk_Paciente' => 2,
                'Fk_Doctor' => 2,
                'Fk_Sucursal' => 1,
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Titulo_Cita' => 'Consulta Pediátrica - Control Niño',
                'Descripcion' => 'Control pediátrico de rutina',
                'Fecha_Cita' => now()->addDays(1)->format('Y-m-d'),
                'Hora_Inicio' => '14:00:00',
                'Hora_Fin' => '14:30:00',
                'Estado_Cita' => 'Confirmada',
                'Tipo_Cita' => 'Control',
                'Consultorio' => 'C003',
                'Costo' => 55.00,
                'Notas_Adicionales' => 'Control de crecimiento y desarrollo',
                'Fk_Paciente' => 3,
                'Fk_Doctor' => 3,
                'Fk_Sucursal' => 1,
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Titulo_Cita' => 'Consulta Ginecológica - Control',
                'Descripcion' => 'Control ginecológico anual',
                'Fecha_Cita' => now()->addDays(3)->format('Y-m-d'),
                'Hora_Inicio' => '08:00:00',
                'Hora_Fin' => '08:40:00',
                'Estado_Cita' => 'Pendiente',
                'Tipo_Cita' => 'Control',
                'Consultorio' => 'CN001',
                'Costo' => 70.00,
                'Notas_Adicionales' => 'Papanicolau anual',
                'Fk_Paciente' => 4,
                'Fk_Doctor' => 4,
                'Fk_Sucursal' => 2,
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Titulo_Cita' => 'Consulta Ortopédica - Dolor Rodilla',
                'Descripcion' => 'Evaluación por dolor en rodilla derecha',
                'Fecha_Cita' => now()->addDays(4)->format('Y-m-d'),
                'Hora_Inicio' => '15:00:00',
                'Hora_Fin' => '15:45:00',
                'Estado_Cita' => 'Pendiente',
                'Tipo_Cita' => 'Consulta',
                'Consultorio' => 'CS001',
                'Costo' => 75.00,
                'Notas_Adicionales' => 'Traer radiografías previas si las tiene',
                'Fk_Paciente' => 5,
                'Fk_Doctor' => 5,
                'Fk_Sucursal' => 3,
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Titulo_Cita' => 'Consulta General - Primera Vez',
                'Descripcion' => 'Primera consulta médica general',
                'Fecha_Cita' => now()->addDays(5)->format('Y-m-d'),
                'Hora_Inicio' => '11:00:00',
                'Hora_Fin' => '11:30:00',
                'Estado_Cita' => 'Pendiente',
                'Tipo_Cita' => 'Consulta',
                'Consultorio' => 'C001',
                'Costo' => 45.00,
                'Notas_Adicionales' => 'Nuevo paciente, traer documentos de identidad',
                'Fk_Paciente' => 2,
                'Fk_Doctor' => 1,
                'Fk_Sucursal' => 1,
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'Titulo_Cita' => 'Control Cardiológico - Seguimiento',
                'Descripcion' => 'Control de seguimiento cardiológico',
                'Fecha_Cita' => now()->addDays(6)->format('Y-m-d'),
                'Hora_Inicio' => '16:00:00',
                'Hora_Fin' => '16:45:00',
                'Estado_Cita' => 'Pendiente',
                'Tipo_Cita' => 'Control',
                'Consultorio' => 'C002',
                'Costo' => 80.00,
                'Notas_Adicionales' => 'Revisar medicación actual',
                'Fk_Paciente' => 4,
                'Fk_Doctor' => 2,
                'Fk_Sucursal' => 1,
                'ID_H_O_D' => 'HOSP001',
                'Agregado_Por' => 'Sistema',
                'Agregado_El' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        foreach ($agendas as $agenda) {
            DB::table('agendas')->insert($agenda);
        }

        // Insertar datos de ejemplo en agendas_medicas
        $agendas_medicas = [
            [
                'agenda_id' => 1,
                'doctor_id' => 1,
                'paciente_id' => 1,
                'consultorio_id' => 1,
                'enfermero_id' => null,
                'tipo_cita' => 'control',
                'estado' => 'confirmada',
                'fecha_cita' => now()->addDays(1)->format('Y-m-d'),
                'hora_inicio' => '09:00:00',
                'hora_fin' => '09:30:00',
                'duracion_minutos' => 30,
                'motivo_consulta' => 'Control rutinario de salud general',
                'sintomas' => 'Ninguno reportado',
                'observaciones_paciente' => 'Se siente bien, solo quiere control de presión',
                'observaciones_medico' => null,
                'procedimiento_id' => null,
                'procedimientos_adicionales' => null,
                'equipamiento_requerido' => 'Tensiómetro, estetoscopio',
                'diagnostico' => null,
                'tratamiento' => null,
                'indicaciones' => null,
                'fecha_proximo_control' => now()->addMonths(3)->format('Y-m-d'),
                'costo_consulta' => 45.00,
                'costo_procedimientos' => 0.00,
                'total_facturado' => 45.00,
                'metodo_pago' => 'efectivo',
                'facturado' => false,
                'observaciones' => 'Paciente en buen estado general',
                'datos_adicionales' => json_encode(['presion_arterial' => '120/80', 'peso' => '65kg']),
                'creado_por' => 'Sistema',
                'actualizado_por' => null,
                'fecha_confirmacion' => now(),
                'fecha_inicio_real' => null,
                'fecha_fin_real' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'agenda_id' => 2,
                'doctor_id' => 2,
                'paciente_id' => 2,
                'consultorio_id' => 2,
                'enfermero_id' => null,
                'tipo_cita' => 'primera_vez',
                'estado' => 'programada',
                'fecha_cita' => now()->addDays(2)->format('Y-m-d'),
                'hora_inicio' => '10:00:00',
                'hora_fin' => '10:45:00',
                'duracion_minutos' => 45,
                'motivo_consulta' => 'Evaluación cardiológica por dolor en el pecho',
                'sintomas' => 'Dolor en el pecho ocasional, fatiga',
                'observaciones_paciente' => 'El dolor aparece al hacer ejercicio',
                'observaciones_medico' => null,
                'procedimiento_id' => null,
                'procedimientos_adicionales' => 'Electrocardiograma',
                'equipamiento_requerido' => 'Electrocardiógrafo, monitor cardíaco',
                'diagnostico' => null,
                'tratamiento' => null,
                'indicaciones' => null,
                'fecha_proximo_control' => null,
                'costo_consulta' => 80.00,
                'costo_procedimientos' => 25.00,
                'total_facturado' => 105.00,
                'metodo_pago' => 'tarjeta',
                'facturado' => false,
                'observaciones' => 'Paciente con factores de riesgo cardiovascular',
                'datos_adicionales' => json_encode(['presion_arterial' => '140/90', 'colesterol_total' => '220mg/dl']),
                'creado_por' => 'Sistema',
                'actualizado_por' => null,
                'fecha_confirmacion' => null,
                'fecha_inicio_real' => null,
                'fecha_fin_real' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'agenda_id' => 3,
                'doctor_id' => 3,
                'paciente_id' => 3,
                'consultorio_id' => 3,
                'enfermero_id' => null,
                'tipo_cita' => 'control',
                'estado' => 'confirmada',
                'fecha_cita' => now()->addDays(1)->format('Y-m-d'),
                'hora_inicio' => '14:00:00',
                'hora_fin' => '14:30:00',
                'duracion_minutos' => 30,
                'motivo_consulta' => 'Control pediátrico de rutina',
                'sintomas' => 'Ninguno reportado',
                'observaciones_paciente' => 'Madre reporta que el niño come bien y duerme bien',
                'observaciones_medico' => null,
                'procedimiento_id' => null,
                'procedimientos_adicionales' => null,
                'equipamiento_requerido' => 'Balanza, tallímetro, estetoscopio pediátrico',
                'diagnostico' => null,
                'tratamiento' => null,
                'indicaciones' => null,
                'fecha_proximo_control' => now()->addMonths(2)->format('Y-m-d'),
                'costo_consulta' => 55.00,
                'costo_procedimientos' => 0.00,
                'total_facturado' => 55.00,
                'metodo_pago' => 'efectivo',
                'facturado' => false,
                'observaciones' => 'Niño en buen estado de desarrollo',
                'datos_adicionales' => json_encode(['peso' => '18kg', 'talla' => '105cm', 'imc' => '16.3']),
                'creado_por' => 'Sistema',
                'actualizado_por' => null,
                'fecha_confirmacion' => now(),
                'fecha_inicio_real' => null,
                'fecha_fin_real' => null,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        foreach ($agendas_medicas as $agenda_medica) {
            DB::table('agendas_medicas')->insert($agenda_medica);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Eliminar datos en orden inverso para evitar problemas de foreign keys
        DB::table('agendas_medicas')->truncate();
        DB::table('agendas')->truncate();
        DB::table('pacientes')->truncate();
        DB::table('doctores')->truncate();
        DB::table('consultorios')->truncate();
        DB::table('sucursales')->truncate();
    }
};
